version: "2.2"
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 8080:80